center/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns

from django.conf import settings


admin.autodiscover()
urlpatterns = i18n_patterns(
      path('jet/', include('jet.urls', 'jet')),  # Django JET URLS
        path('', include('payment.urls')),  # Django JET URLS

    path('admin/', admin.site.urls),

)
# if settings.DEBUG:
#     import debug_toolbar
#     urlpatterns = [
#         path('__debug__/', include(debug_toolbar.urls)),

#         # For django versions before 2.0:
#         # url(r'^__debug__/', include(debug_toolbar.urls)),

#     ] + urlpatterns

payment/urls.py
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from .views import *




urlpatterns = [
   #  path(
   #      'country-autocomplete/',
   #      CountryAutocomplete.as_view(),
   #      name='country-autocomplete',
   #  ),
    path('search/', search_users, name='search_users'),
    path('debt/', debt, name='debt'),

]

payment/models.py
from django.db import models
from django.utils import timezone
import datetime
from django.utils.html import format_html
from branch.models import *
# MONTHS = (
# 	('Yanvar', 'Yanvar'),
# 	('Fevral', 'Fevral'),
# 	('Mart','Mart'),
# 	('Aprel','Aprel'),
# 	('May', 'May'),
# 	('Iyun', 'Iyun'),
# 	('Iyul', 'Iyul'),
# 	('Avgust','Avgust'),
# 	('Sentyabr','Sentyabr'),
# 	('Oktyabr','Oktyabr'),
# 	('Noyabr','Noyabr'),
# 	('Dekabr','Dekabr'),
# 	)
MONTHS = ['Yanvar',
	'Fevral',
	'Mart',
	'Aprel',
	'May', 
	'Iyun',
	'Iyul',
	'Avgust',
	'Sentyabr',
	'Oktyabr',
	'Noyabr',
	'Dekabr',
	]
YEARS = (
	(2020, 2020),
	(2021,2021),
	(2022,2022),
	(2023,2023),
	(2024, 2024),
	(2025, 2025),
	)

YEAR_CHOICES = [(f'{m} {y}',f'{m} {y}') for y in range(2020, 2026) for m in MONTHS]

class Teacher(models.Model):
	branch = models.ForeignKey(Branch, on_delete=models.CASCADE, null=True)
	name = models.CharField(max_length=50, blank=True, verbose_name="Ismi")
	subject = models.CharField(max_length=100, blank=True, verbose_name="Fan")
	official = models.IntegerField(default=0, verbose_name="rasmiy oylik")

	def __str__(self):
		return self.name 

	class Meta:
		verbose_name="O'qituvchi"
		verbose_name_plural="O'qituvchilar"

class Salary(models.Model):
	branch = models.ForeignKey(Branch, on_delete=models.CASCADE, null=True)

	teacher = models.ForeignKey(Teacher, related_name='salaries',on_delete=models.CASCADE)
	period = models.CharField(choices=YEAR_CHOICES,
	     	default=f'{MONTHS[datetime.datetime.now().month-1]} {datetime.datetime.now().year}', max_length=20)
	date = models.DateTimeField(auto_now_add=True, verbose_name="to'langan san'a")
	paid = models.IntegerField(default=0, verbose_name="Hisoblandi")
	official = models.IntegerField(default=0, verbose_name="rasmiy oylik")

	class Meta:
		verbose_name="Oylik"
		verbose_name_plural="Oyliklar"
		unique_together = ('teacher','period')

	def __str__(self):
		return f'{self.teacher}ning oyligi'
# class Lesson(models.Model):
# 	teacher = models.ForeignKey(Teacher, verbose_name="o'qituvchi",on_delete=models.CASCADE)
# 	schedule = models.CharField(max_length=100)

# 	def __str__(self):
# 		return self.schedule


class Student(models.Model):
	branch = models.ForeignKey(Branch, on_delete=models.CASCADE, null=True)
	charachteristics = models.TextField(max_length=30, blank=True, verbose_name="Ta'rif")
	name = models.CharField(max_length=50, blank=True, verbose_name="FISH")
	phone_number = models.CharField(max_length=20, blank=True,default='-', verbose_name="Tel. nomeri")
	fathers_phone = models.CharField(max_length=20, blank=True,default='-', verbose_name="Otasing tel.")
	mothers_phone = models.CharField(max_length=20, blank=True,default='-', verbose_name="Onasing tel.")

	def __str__(self):
		return self.name 

	class Meta:
		verbose_name="Talaba"
		verbose_name_plural="Talabalar"
	# @property
	# def model_two_other_field(self):
	# 	return ', '.join([m2.percent for m2 in self.payments.all()])


class Contract(models.Model):
	branch = models.ForeignKey(Branch, on_delete=models.CASCADE, null=True)

	TIMES = [(f'{t}.00', f'{t}.00') for t in range(6, 24)]
	teacher = models.ForeignKey(Teacher, related_name='contracts', verbose_name="o'qituvchisi",on_delete=models.CASCADE)
	student = models.ForeignKey(Student, related_name='contracts', verbose_name="o'quvchisi",on_delete=models.CASCADE)
	percent = models.IntegerField(default=50)
	price = models.IntegerField(default=0)
	parity = models.CharField(max_length=5, verbose_name='Kun', choices=(
																		('Toq', 'Toq'),
																		('Juft','Juft'), ), default=1
																						)
	group_time = models.CharField(max_length=5, choices=TIMES, default=1)
	date_joined = models.DateTimeField(auto_now_add=True)
	status = models.BooleanField(default=True)
	
	class Meta:
		unique_together = ('teacher', 'student',)
		verbose_name="Shartnoma"
		verbose_name_plural="Shartnomalar"
	def __str__(self):
		return f'{self.teacher.name}-{self.student.name}'

class Payment(models.Model):
	branch = models.ForeignKey(Branch, on_delete=models.CASCADE, null=True)
	kassir = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

	MONTH_CHOICE = [(m,m) for m in range(1,13)]
	contract = models.ForeignKey(Contract, related_name='payments',on_delete=models.CASCADE)
	period = models.CharField(choices=YEAR_CHOICES,
	     	default=f'{MONTHS[datetime.datetime.now().month-1]} {datetime.datetime.now().year}', max_length=20, verbose_name="To'lov oyi")
	teacher = models.ForeignKey(Teacher, blank=True, related_name='payments', verbose_name="o'qituvchisi",on_delete=models.CASCADE)
	student = models.ForeignKey(Student, blank=True, related_name='payments', verbose_name="o'quvchisi",on_delete=models.CASCADE)	
	date = models.DateTimeField(auto_now_add=True, verbose_name="san'a")
	has_to_pay = models.IntegerField(default=0, verbose_name="To'lanishi kerak")
	percent = models.IntegerField(default=50, verbose_name='foiz')
	paid = models.IntegerField(default=0, verbose_name="To'landi")

	class Meta:
		unique_together=('teacher', 'student' , 'period')
		verbose_name="To'lov"
		verbose_name_plural="To'lovlar"
	def save(self, *args, **kwargs):
		#self.contract = Contract.objects.get_or_create(teacher=self.teacher, student=self.student)
		if self.contract:
			#self.percent = self.contract.percent
			self.teacher = self.contract.teacher
			self.student = self.contract.student
			if not self.has_to_pay:
				self.has_to_pay = self.contract.price
		super().save(*args,**kwargs)

payment/forms.py
# from dal import autocomplete

# from django import forms
# from .models import Student

# class StudentForm(forms.ModelForm):
#     name = forms.ModelChoiceField(
#         queryset=Student.objects.all(),
#         widget=autocomplete.ModelSelect2(url='country-autocomplete')
#     )

#     class Meta:
#         model = Student
#         fields = ('__all__')

payment/views.py
from django.conf.urls.static import static
from .models import Student, Teacher, Contract
from django.shortcuts import render
from django.http import JsonResponse
from django.db.models import Q, Sum, F
from django.urls import reverse
from django.shortcuts import render, redirect


def search_users(request):
    q = request.POST.get('search')
    user = Student.objects.filter(Q(name__icontains=q) )[:5]
    data={'data':[]}
    
    for u in user:
      
        data['data'].append(
        {
            'username': u.name,
            'url': f'/uz/admin/payment/student/{u.id}/change/',
        })
        
    # else:
    #     users_list = {'success': 'false'}
    print(data)
    return render(request,'m.html',data)


def debt(request):
    if request.method=="POST":
        teacher = Teacher.objects.get(id=request.POST.get('teacher'))
        time = request.POST.get('time')
        parity = request.POST.get('parity')
        data = Contract.objects.filter(teacher=teacher, group_time=time, parity=parity).annotate(debt=Sum(F('payments__has_to_pay')-F('payments__paid'))).filter(debt__gt=0)
        return render(request, 'print.html',{ 'data':data})
    teachers  = Teacher.objects.all()
    TIMES = [f'{t}.00' for t in range(6, 24)]
    return render(request,'debt.html',{'teachers':teachers, 'times':TIMES})

payment/templates/debt.html
{%extends "admin/base_site.html"%}
{% block extrahead %}





<script type="text/javascript" src="/uz/admin/jsi18n/"></script>
<script type="text/javascript" src="/static/admin/js/vendor/jquery/jquery.js"></script>
<script type="text/javascript" src="/static/admin/js/jquery.init.js"></script>
<script type="text/javascript" src="/static/admin/js/core.js"></script>
<script type="text/javascript" src="/static/admin/js/inlines.js"></script>
<script type="text/javascript" src="/static/admin/js/admin/RelatedObjectLookups.js"></script>
<script type="text/javascript" src="/static/admin/js/change_form.js"></script>
<script type="text/javascript" src="/static/admin/js/actions.js"></script>
<script type="text/javascript" src="/static/admin/js/prepopulate_init.js"></script>
<script type="text/javascript" src="/static/admin/js/urlify.js"></script>
<script type="text/javascript" src="/static/admin/js/prepopulate.js"></script>
<script type="text/javascript" src="/static/admin/js/vendor/xregexp/xregexp.js"></script>
{% endblock %}}
{% block content %}
<form method="POST" action="">
	{% csrf_token%}
    <select name="teacher" id="id_contracts-0-teacher" tabindex="-1" class="select2-hidden-accessible" aria-hidden="true">
  <option value="">---------</option>

{%for t in teachers %}
<option value="{{t.id}}">{{t.name}}</option>
{%endfor %}

</select>
    
    <select name="time" id="id_contracts-0-teacher" tabindex="-1" class="select2-hidden-accessible" aria-hidden="true">
  <option value="">---------</option>

{%for t in times %}
<option value="{{t}}">{{t}}</option>
{%endfor %}

</select>
    <select name="parity" id="id_contracts-0-teacher" tabindex="-1" class="select2-hidden-accessible" aria-hidden="true">
  <option value="">---------</option>

<option value="Toq">Toq</option>
<option value="Juft">Juft</option>


</select>
<input type="submit" value="Jo'natish" class="default" name="_save">
    </form>


{% endblock %}

payment/templates/m.html
        <datalist class="search-results" id="my-list" name="my-list">

{%for i in data %}
     <option value="{{i.username}}"></option>
{%endfor%}
</datalist>

payment/templates/new.html
{% extends "admin/change_list.html" %}
{% load i18n admin_urls static admin_modify %}{% load static %}
{% load i18n static %}
{% block extrastyle %}
    <style>
       .field-temp .select2-container--jet {
display: none;        }

  </style>
    {% endblock %}
{% block search %}


<!-- <div class="frmSearch">
    <input type="text" id="search-box" placeholder="Country Name" />
    <div id="suggesstion-box"></div>
</div> -->
<!-- <div class="up__search">
                        <form method="get" action="" id="search-userform">
                            <div class="s-con">
                                <input type="text" id="search-user" name="search" class="f-search" placeholder="Search..." autocomplete="off">
                                <button type="submit" class="btn-s"><i class="search icon"></i></button>
                            </div>
                            <div class="rs-container">
                                <div class="results"></div>
                                <div class="view-all">
                                    <a class="rs-item"></a>
                                </div>
                            </div>
                        </form>
                    </div> -->
             
{% endblock %}

payment/templates/print.html
<!DOCTYPE html>
<html>
<head>
	<title>Pechat uchun</title>
</head>
<body>
{%for t in data%}
{{forloop.counter}}. {{t.student.name}} - {{t.debt}}
{% endfor%}
</body>
</html>

payment/templates/r.html
			<table 	>
<tbody>
	{%for  i in pays %}
<tr class="row1">
<!-- 	<td class="field-phone_number">{{i.date_joined|date:"d.m.y"}}</td>
 -->
 <td  width=1 class="form-row">
            <div class=" field-temp">
            	
           
            
              
    <select name="teacher" required id="id_teacher" multiple>
</select>
        <a class="related-widget-wrapper-link change-related" id="add_id_teacher"
            href="/uz/admin/payment/payment/?student__id__exact={{i.student.id}}&teacher__id__exact={{i.teacher.id}}"
            title="Добавить ещё один объект типа "teacher=""><span class="sidebar-link-icon icon-data"></span></a>

            </div>
        </td>
<td class="field-phone_number">{{i.teacher.name}}</td>

<td class="field-phone_number">{{i.teacher.subject}}</td>
<td class="field-name"><input size="2"  id="tochange-{{i.id}}" type="text" name="" value="{%if i.debt == None %}0{%else%}{{i.debt}}{%endif%}" maxlength="50" >
</td>
</tr>
{% endfor %}

</tbody>
</table>
<td>
			<table 	>
<tbody>
{%for i, v in d %}
<tr class="row1">
<td><input  class="topay" size="2" id="topay-{{i.contract.id}}"type="text" name="topay-{{i.id}}" value="{%if i.has_to_pay == None %}{{i.contract.price}}{%else%}{{i.has_to_pay}}{%endif%}" maxlength="50" >
<td class="field-name"><input size="3" type="text" name="" id="special-{{i.contract.id}}" value="={{v}}" maxlength="50" >
</td>
</tr>
{% endfor %}


</tbody>
</table></td>
<td>
			<table 	>
<tbody>
{%for  i, v in d %}
<tr class="row1">
<td class="tochange"><input class="tochange" size="1" type="text" name="params-{{i.id}}" value="{{i.paid}}" maxlength="50" >
</td>
</tr>
{% endfor %}
</tbody>
</table></td>
<td>
			<table 	>
<tbody>
{%for  i, v in d %}
<tr class="row1">
<td class="field-name"><input size="5" type="text" name="" value="{%if i.has_to_pay == None %} - {%else%}{{i.date|date:'d.m.y'}}{%endif%}" maxlength="50" >
</td>
</tr>
{% endfor %}
</tbody>
</table></td>

payment/templates/r1.html
<div id={{id}}-0>{{debt}}</div>
<td ><input class="{{id}}" size="2" id="{{id}}-1" name="pr_paid-{{previous.id}}" type="text" value="{{previous.paid}}"></td>
<td ><input class="{{id}}" size="2" id="{{id}}-2" name="pr_official-{{previous.id}}" type="text" value="{{previous.official}}"></td>
<td><input class="{{id}}" size="2" id="{{id}}-3" type="text" value="{{earned.previous}}"></td>
<td ><input class="{{id}}" size="2" id="{{id}}-4" type="text" value="{{previous_debt}}"></td>
<td><input class="{{id}}" size="2" id="{{id}}-5" name="cur_paid-{{current.id}}" type="text" value="{{current.paid}}"></td>
<td ><input class="{{id}}" size="2" id="{{id}}-6" name="cur_official-{{current.id}}" type="text" value="{{current.official}}"></td>
<td ><input class="{{id}}" size="2" id="{{id}}-7" type="text" value="{{earned.current}}"></td>
<td ><input class="{{id}}" size="2" id="{{id}}-8" type="text" value="{{current_debt}}"></td>

payment/templates/s.html
{% extends "admin/change_list.html" %}
{% load i18n admin_urls static admin_modify %}{% load static %}
{% load i18n static %}
{% block extrastyle %}
    <style>
       .field-temp .select2-container--jet {
display: none;        }
input[list] {
    width: 450px;
}
#tempor{
    background-color: yellow;
    font-size: large;
}
  </style>
    {% endblock %}
{% block search %}
<div class="module initialized" id="changelist">
      

<div id="toolbar" class="initialized">

            
  
<input class="kl" id="search-box" type="text" name="city" list="my-list">
<a  href="{% url 'debt' %}"  target="_blank"><input type="submit"value="QARZDORLAR" id="tempor" name="_save"></a>
    <div class="kl" id="search-results">

       <!--  <datalist class="search-results" id="cityname">
      <option value="Boston">
      <option value="Cambridge">
    </datalist> -->
    </div>
            

        

<!-- <div class="frmSearch">
    <input type="text" id="search-box" placeholder="Country Name" />
    <div id="suggesstion-box"></div>
</div> -->
<!-- <div class="up__search">
                        <form method="get" action="" id="search-userform">
                            <div class="s-con">
                                <input type="text" id="search-user" name="search" class="f-search" placeholder="Search..." autocomplete="off">
                                <button type="submit" class="btn-s"><i class="search icon"></i></button>
                            </div>
                            <div class="rs-container">
                                <div class="results"></div>
                                <div class="view-all">
                                    <a class="rs-item"></a>
                                </div>
                            </div>
                        </form>
                    </div> -->
                </div></div>

{% endblock %}